import 'package:flutter/material.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/Generated45minWidget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedOVERVIEWWidget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedAntdesignclockcirclefilledWidget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedHardWidget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedNotofireWidget1.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedEXERCISELISTWidget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedButtonprimaryWidget2.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedAmetminimmollitnondeseruntullamcoestsitaliquadolordoame5.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedUpperBodyAttackWidget2.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget1/generated/GeneratedGroup1Widget1.dart';

/* Frame home screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomescreenWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 918.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: -8.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 358.0,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 93.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 88.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 30.0,
                child: GeneratedUpperBodyAttackWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 67.0,
                child:
                    GeneratedAmetminimmollitnondeseruntullamcoestsitaliquadolordoame5(),
              ),
              Positioned(
                left: 16.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 19.0,
                child: GeneratedOVERVIEWWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 16.0,
                child: GeneratedEXERCISELISTWidget(),
              ),
              Positioned(
                left: 138.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 20.0,
                child: GeneratedHardWidget(),
              ),
              Positioned(
                left: 119.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedNotofireWidget1(),
              ),
              Positioned(
                left: 211.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 17.0,
                child: Generated45minWidget(),
              ),
              Positioned(
                left: 191.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedAntdesignclockcirclefilledWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 45.0,
                child: GeneratedButtonprimaryWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 592.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 703.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 129.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 39.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 129.0,
                top: 733.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 39.0,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 129.0,
                top: 844.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 39.0,
                child: GeneratedGroup6Widget(),
              )
            ]),
      ),
    ));
  }
}
