import 'package:flutter/material.dart';
import 'package:flutterapp/gym_appapp/generatedsplashscreenwidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/gym_appapp/generatedsplashscreenwidget/generated/GeneratedButtonprimaryWidget1.dart';
import 'package:flutterapp/gym_appapp/generatedsplashscreenwidget/generated/GeneratedButtonprimaryWidget.dart';
import 'package:flutterapp/gym_appapp/generatedsplashscreenwidget/generated/GeneratedBecomeaCoachWidget.dart';
import 'package:flutterapp/gym_appapp/generatedsplashscreenwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/gym_appapp/generatedsplashscreenwidget/generated/GeneratedBecomestrongerwithourworkoutplansWidget.dart';
import 'package:flutterapp/gym_appapp/generatedsplashscreenwidget/generated/GeneratedAmetminimmollitnondeseruntullamcoestsitaliquadolordoame.dart';
import 'package:flutterapp/gym_appapp/generatedsplashscreenwidget/generated/GeneratedRectangle1Widget.dart';

/* Frame Splashscreen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 141.0,
                top: 718.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 16.0,
                child: GeneratedBecomeaCoachWidget(),
              ),
              Positioned(
                left: -33.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 440.0,
                height: 535.0,
                child: GeneratedImage1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 198.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 95.0,
                top: 463.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 44.0,
                child: GeneratedBecomestrongerwithourworkoutplansWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 91.0,
                child:
                    GeneratedAmetminimmollitnondeseruntullamcoestsitaliquadolordoame(),
              ),
              Positioned(
                left: 16.0,
                top: 602.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 45.0,
                child: GeneratedButtonprimaryWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 655.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 45.0,
                child: GeneratedButtonprimaryWidget1(),
              )
            ]),
      ),
    ));
  }
}
