import 'package:flutter/material.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedBOTTOMTABBARWidget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedSPECIALOFFERSWidget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedRECOMMENDEDWORKOUTSWidget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedSundayJanuary102020Widget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedAmetminimmollitnondeseruntullamcoestsitaliquadolordoame4.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedAntdesignstarfilledWidget1.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedSearchanythingWidget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedEvasearchfillWidget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedAntdesignstarfilledWidget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedNotofireWidget.dart';
import 'package:flutterapp/gym_appapp/generatedhomescreenwidget/generated/GeneratedLetscrushitHariWidget.dart';

/* Frame home screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomescreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          clipBehavior: Clip.none,
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  clipBehavior: Clip.none,
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 918.0,
                      child: GeneratedRectangle1Widget1(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 185.0,
                      right: null,
                      bottom: null,
                      width: 159.0,
                      height: 16.0,
                      child: GeneratedRECOMMENDEDWORKOUTSWidget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 463.0,
                      right: null,
                      bottom: null,
                      width: 96.0,
                      height: 16.0,
                      child: GeneratedSPECIALOFFERSWidget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 80.0,
                      right: null,
                      bottom: null,
                      width: 147.0,
                      height: 23.0,
                      child: GeneratedLetscrushitHariWidget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 62.0,
                      right: null,
                      bottom: null,
                      width: 180.0,
                      height: 20.0,
                      child: GeneratedSundayJanuary102020Widget(),
                    ),
                    Positioned(
                      left: 165.0,
                      top: 82.0,
                      right: null,
                      bottom: null,
                      width: 16.0,
                      height: 16.0,
                      child: GeneratedNotofireWidget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 116.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 45.0,
                      child: GeneratedRectangle4Widget(),
                    ),
                    Positioned(
                      left: 314.0,
                      top: 116.0,
                      right: null,
                      bottom: null,
                      width: 45.0,
                      height: 45.0,
                      child: GeneratedRectangle5Widget(),
                    ),
                    Positioned(
                      left: 41.0,
                      top: 132.0,
                      right: null,
                      bottom: null,
                      width: 108.0,
                      height: 15.0,
                      child: GeneratedSearchanythingWidget(),
                    ),
                    Positioned(
                      left: 325.0,
                      top: 126.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedEvasearchfillWidget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 209.0,
                      right: null,
                      bottom: null,
                      width: 236.0,
                      height: 230.0,
                      child: GeneratedGroup1Widget(),
                    ),
                    Positioned(
                      left: 14.0,
                      top: 593.0,
                      right: null,
                      bottom: null,
                      width: 347.0,
                      height: 230.0,
                      child: GeneratedGroup3Widget(),
                    ),
                    Positioned(
                      left: 260.0,
                      top: 209.0,
                      right: null,
                      bottom: null,
                      width: 236.0,
                      height: 230.0,
                      child: GeneratedGroup2Widget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 487.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 86.0,
                      child: GeneratedRectangle9Widget(),
                    ),
                    Positioned(
                      left: 91.0,
                      top: 505.0,
                      right: null,
                      bottom: null,
                      width: 257.0,
                      height: 48.0,
                      child:
                          GeneratedAmetminimmollitnondeseruntullamcoestsitaliquadolordoame4(),
                    ),
                    Positioned(
                      left: 31.0,
                      top: 504.0,
                      right: null,
                      bottom: null,
                      width: 49.0,
                      height: 49.0,
                      child: GeneratedAntdesignstarfilledWidget(),
                    ),
                    Positioned(
                      left: 31.0,
                      top: 517.0,
                      right: null,
                      bottom: null,
                      width: 36.0,
                      height: 36.0,
                      child: GeneratedAntdesignstarfilledWidget1(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 732.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 80.0,
              child: GeneratedBOTTOMTABBARWidget(),
            )
          ]),
    ));
  }
}
