import 'package:flutter/material.dart';

/* Frame iPhone 11 Pro / X - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 255, 255, 255),
          ),
        ),
      ),
    ));
  }
}
